groups/urls.py
from django.conf.urls import patterns, url
from groups import views
from django.contrib.auth.decorators import login_required, permission_required

urlpatterns = patterns('',
    url(r'^$', login_required(views.GroupListView.as_view()), name='group_list'),
    url(r'^(?P<pk>\d+)/$', login_required(views.GroupDetailView.as_view()), name='group_detail'),
    url(r'^add/$', login_required(views.GroupCreateView.as_view()), name='group_add'),
    url(r'^autocomplete_member/', login_required(views.autocomplete_member), name='autocomplete_member'),
    url(r'^(?P<pk>\d+)/update/$', login_required(views.GroupUpdateView.as_view()), name='group_update'),
    url(r'^(?P<pk>\d+)/delete/$', login_required(views.GroupDeleteView.as_view()), name='group_delete'),
    url(r'^(?P<pk>\d+)/search_member_for_group/$', login_required(views.search_member_for_group), name='search_member_for_group'),
    url(r'^(?P<group_id>\d+)/add_member_to_group/$', login_required(views.add_member_to_group), name='add_member_to_group'),
    url(r'^(?P<group_id>\d+)/register_meeting/$', login_required(views.register_meeting), name='register_meeting'),
    url(r'^(?P<group_id>\d+)/submit_meeting/$', login_required(views.submit_meeting), name='submit_meeting'),
    url(r'^(?P<group_id>\d+)/remove_member_from_group/(?P<member_id>\d+)$', login_required(views.remove_member_from_group), name='remove_member_from_group'),
)

meuatreze/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from meuatreze import views


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'meuatreze.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^pessoal/', views.personal, name='personal'),
    url(r'^members/', include('members.urls', namespace='members')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'logged_out.html'}),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^$', views.index, name='index'),
)

groups/models.py
from django.db import models
from members.models import Member

class Group(models.Model):
	name = models.CharField(max_length=50)
	leader = models.ForeignKey('members.Member')
	members = models.ManyToManyField('members.Member', related_name='member_groups', blank=True)

	def __unicode__(self):
		return self.name

class Meeting(models.Model):

	# A Meeting has a type that can be either STUDY or RELATIONSHIP
	
	STUDY = 'ST'
	RELATIONSHIP = 'RE'

	MEETING_TYPE = (
			(STUDY, 'Estudo'),
			(RELATIONSHIP, 'Relacionamento'),
	)

	group = models.ForeignKey('Group')
	date = models.DateField(auto_now_add=True)
	members_who_attended = models.ManyToManyField('members.Member', blank=True)
	comments = models.TextField()
	type = models.CharField(max_length=2, choices=MEETING_TYPE, default=STUDY)

	def __unicode__(self):
		return self.group.name

members/models.py
from django.db import models
from django.contrib.auth.models import User

class Member(models.Model):
	user = models.OneToOneField(User, unique=True, null=True)
	name = models.CharField(max_length=200)
	email = models.EmailField(max_length=200)
	is_leader = models.BooleanField(default=False)
	is_department_leader = models.BooleanField(default=False)

	def __unicode__(self):
		return self.name

groups/views.py
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView
from django.shortcuts import render, redirect
from django.http import HttpResponse

from members.models import Member
from groups.models import Group, Meeting

import json
from datetime import datetime

def autocomplete_member(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        members = Member.objects.filter(name__icontains = q )[:20]
        results = []
		
        for member in members:
            member_json = {}
            member_json['id'] = member.id
            member_json['label'] = member.name
            member_json['value'] = member.name
            results.append(member_json)

        data = json.dumps(results)
    else:
        data = 'fail'

    mimetype = 'application/json'
    return HttpResponse(data, mimetype)



def search_member_for_group(request, pk):
	""" Receives pk as the key for the Group which we want to add members to """
	context = { 'group_id': pk}
	return render(request, 'groups/search_member_for_group.html', context)



def remove_member_from_group(request, group_id, member_id):
	member = Member.objects.get(pk=member_id)
	group = Group.objects.get(pk=group_id)

	group.members.remove(member)
	group.save()

	context = {'member': member, 'group': group}
	
	return render(request, 'groups/member_removed_from_group.html', context)



def add_member_to_group(request, group_id):
	new_group_member = Member.objects.get(pk=request.POST['member_id'])
	group = Group.objects.get(pk=group_id)
	
	group.members.add(new_group_member)
	group.save()

	context = {'new_group_member': new_group_member.name, 'group_name': group.name}

	return render(request, 'groups/member_added_to_group_sucess.html', context)



def register_meeting(request, group_id):
	group = Group.objects.get(pk=group_id)
	group_members = group.members.all()
	context = {'group': group, 'group_members': group_members}

	return render(request, 'groups/register_meeting.html', context)



def submit_meeting(request, group_id):
	present_members_ids = request.POST.getlist('members')
	present_members = []

	for member_id in present_members_ids:
		present_members.append(Member.objects.get(pk=member_id))

	group = Group.objects.get(pk=group_id)
	comments = request.POST['comments']
	meeting_type = request.POST['type']
	date = datetime.strptime(request.POST['date'], "%d/%m/%Y").strftime("%Y-%m-%d")

	meeting = Meeting()

	group.meeting_set.add(meeting)

	meeting.group = group
	meeting.type = meeting_type
	meeting.comments = comments
	meeting.date = date
	meeting.members_who_attended = present_members

	meeting.save()

	context = {}

	return render(request, 'groups/submit_meeting.html', context)



class GroupListView(ListView):
	template_name = 'groups/list.html'
	context_object_name = 'group_list'

	def get_queryset(self):
		""" Return all registered members """
		return Group.objects.all()



class GroupDetailView(DetailView):
	model = Group
	template_name = 'groups/detail.html'

	def get_context_data(self, **kwargs):
		context = super(GroupDetailView, self).get_context_data(**kwargs)
		context["group_members"] = context['group'].members.all()
		context["last_meetings"] = Meeting.objects.filter(group=context['group']).order_by('-date')[:5]
		
		return context



class GroupCreateView(CreateView):
	model = Group
	template_name = 'groups/form.html'
	fields = ['name', 'leader']
	success_url = reverse_lazy('groups:group_list')



class GroupUpdateView(UpdateView):
	model = Group
	template_name = 'groups/form.html'
	fields = ['name', 'leader']
	success_url = reverse_lazy('groups:group_list')



class GroupDeleteView(DeleteView):
	model = Group
	template_name = 'groups/confirm_delete.html'
	success_url = reverse_lazy('groups:group_list')

groups/templates/groups/confirm_delete.html
{% extends "base.html" %}

{% block content %}

<form method="post">{% csrf_token %}
    Tem certeza que deseja apagar o grupo "{{ object }}" ?
    <input type="submit" value="Sim" />
</form>

{% endblock %}

groups/templates/groups/detail.html
{% extends "base.html" %}

{% block content %}

<div id="member_info">
	<h3>Dados:</h3>

	<p>Nome: {{ group.name }}</p>
	<p>Líder: {{ group.leader }}</p>

	<p>Membros do GCs: </p>

	{% if group_members %}
		<ul>
			{% for member in group_members %}
        		<li>{{ member.name }} <a href="{% url 'groups:remove_member_from_group' group.id member.id %}">Remover do GC</a></li>
    		{% endfor %}
		</ul>
	{% else %}
		<p>Esse GC ainda não possui nenhum membro.</p>
	{% endif %}

	<p>Últimos GCS: </p>

	{% if last_meetings %}
		<ul>
			{% for meeting in last_meetings %}
        		<li>{{ meeting.date }} - {{ meeting.get_type_display }}</li>
    		{% endfor %}
		</ul>
	{% else %}
		<p>Esse GC ainda não fez nenhuma reunião.</p>
	{% endif %}

</div>

{% endblock %}

groups/templates/groups/form.html
{% extends "base.html" %}

{% block content %}

<h1>Cadastrar Grupo</h1>


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form method="post">

{% csrf_token %}

{{ form.as_p }}

<input type="submit" value="Salvar" />
</form>

{% endblock %}

groups/templates/groups/list.html
{% extends "base.html" %}

{% block content %}

<div class="col-md-8 col-md-offset-2 content_block">

    {% if group_list %}
        <table class="entries_table">
        <tbody>
            <tr>
                <th>Nome</th>
                <th>Líder</th>
                <th>Membros</th>
            </tr>

            {% for group in group_list %}

            <tr>
                <td>
                    <a href="{% url 'groups:group_detail' group.id %}">{{ group.name }}</a>
                </td>
                <td>
                    {{ group.leader }}
                </td>
                <td align="center">
                    {{ group.members.count }}
                </td>
                <td>
                    <a href="{% url 'groups:group_update' group.id %}">Editar</a>
                </td>
                <td>
                    <a href="{% url 'groups:group_delete' group.id %}">Apagar</a>
                </td>
                <td>
                    <a href="{% url 'groups:search_member_for_group' group.id %}">Adicionar Membro</a>
                </td>
                <td>
                    <a href="{% url 'groups:register_meeting' group.id %}">Registrar Encontro</a>
                </td>
            </tr>

            {% endfor %}

        </tbody>
        </table>

    {% if perms.members.add_member %}
    <div class="add_entry">
        <a href="{% url 'groups:group_add' %}">Novo Grupo</a>
    </div>
    {% endif %}


    {% else %}
        <p>Nenhum membro cadastrado.</p>
    {% endif %}

    

</div>

{% endblock %}

groups/templates/groups/member_added_to_group_sucess.html
{% extends "base.html" %}

{% block content %}

<h2>{{ new_group_member }} foi adicionado a {{ group_name }}</h2>

{% endblock %}

groups/templates/groups/member_removed_from_group.html
{% extends "base.html" %}

{% block content %}

<h2>{{ member.name }} foi removido(a) de {{ group.name }}</h2>

{% endblock %}	

groups/templates/groups/register_meeting.html
{% extends "base.html" %}

{% block content %}

<script>
  $(function() {
    $( "#date" ).datepicker({
        dateFormat: 'dd/mm/yy',
        dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
        dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
        dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
        monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
        monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
        nextText: 'Próximo',
        prevText: 'Anterior'
    });
  });
  </script>

<h2>Registrar encontro de GC:</h2>

<form method="post" action="{% url 'groups:submit_meeting' group.id %}">

{% csrf_token %}

{% if group_members %}
    <ul>
    {% for member in group_members %}
        <li>
        	<input type="checkbox" value="{{ member.id }}" name="members">{{ member.name }}
        </li>
    {% endfor %}
    </ul>

    <label for"type">Tipo: </label>
	<select id="id" name="type">
	  <option value="ST">Estudo</option>
	  <option value="RE">Relacionamento</option>
	</select>

	<label for"date">Data: </label>
	<input id="date" name="date" nametype="text" />

    <label for"comments">Comentários: </label>
    <input type="text" id="comments" name="comments" />




    <input type="submit" value="Registrar Encontro" />



{% else %}
    <p>Esse grupo não possui nenhum membro.</p>
{% endif %}

</form>

{% endblock %}

groups/templates/groups/search_member_for_group.html
{% extends "base.html" %}

{% block content %}

<script>
  $(function() {
    $("#member").autocomplete({
      source: "/groups/autocomplete_member/",
      minLength: 2,
      dataType: 'json',
      select: function (event, ui) {
        $('#member_id').val(ui.item.id);
      }
    });
  });
</script>

<div class="ui-widget">
  <form action="{% url 'groups:add_member_to_group' group_id %}" method="post">
      {% csrf_token %}
      <label for="member">Membro: </label>
      <input id="member" name="member">
      <input type="hidden" id="member_id" name="member_id">

      <input type="submit" value="Adicionar" />
  </form>  
</div>

{% endblock %}

groups/templates/groups/submit_meeting.html
{% extends "base.html" %}

{% block content %}

<h2>Encontro registrado</h2>

{% endblock %}