groups/urls.py
from django.conf.urls import patterns, url
from groups import views
from django.contrib.auth.decorators import login_required, permission_required

urlpatterns = patterns('',
    url(r'^$', login_required(views.GroupListView.as_view()), name='group_list'),
    url(r'^(?P<pk>\d+)/$', login_required(views.GroupDetailView.as_view()), name='group_detail'),
    url(r'^add/$', login_required(views.GroupCreateView.as_view()), name='group_add'),
    url(r'^autocomplete_member/', login_required(views.autocomplete_member), name='autocomplete_member'),
    url(r'^(?P<pk>\d+)/update/$', login_required(views.GroupUpdateView.as_view()), name='group_update'),
    url(r'^(?P<pk>\d+)/delete/$', login_required(views.GroupDeleteView.as_view()), name='group_delete'),
    url(r'^(?P<pk>\d+)/search_member_for_group/$', login_required(views.search_member_for_group), name='search_member_for_group'),
    url(r'^(?P<group_id>\d+)/add_member_to_group/$', login_required(views.add_member_to_group), name='add_member_to_group'),
    url(r'^(?P<group_id>\d+)/register_meeting/$', login_required(views.register_meeting), name='register_meeting'),
    url(r'^(?P<group_id>\d+)/submit_meeting/$', login_required(views.submit_meeting), name='submit_meeting'),
    url(r'^(?P<group_id>\d+)/remove_member_from_group/(?P<member_id>\d+)$', login_required(views.remove_member_from_group), name='remove_member_from_group'),
)

members/urls.py
from django.conf.urls import patterns, url
from members import views
from django.contrib.auth.decorators import login_required, permission_required


urlpatterns = patterns('',
    url(r'^$', login_required(views.MemberListView.as_view()), name='member_list'),
    url(r'^(?P<pk>\d+)/$', login_required(views.MemberDetailView.as_view()), name='member_detail'),
    url(r'^add/$', login_required(views.MemberCreateView.as_view()), name='member_add'),
    url(r'^(?P<pk>\d+)/update/$', login_required(views.MemberUpdateView.as_view()), name='member_update'),
    url(r'^(?P<pk>\d+)/delete/$', login_required(views.MemberDeleteView.as_view()), name='member_delete'),
)

meuatreze/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView
from meuatreze import views


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'meuatreze.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^pessoal/', views.personal, name='personal'),
    url(r'^members/', include('members.urls', namespace='members')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'logged_out.html'}),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^$', views.index, name='index'),
)

members/models.py
from django.db import models
from django.contrib.auth.models import User

class Member(models.Model):
	user = models.OneToOneField(User, unique=True, null=True)
	name = models.CharField(max_length=200)
	email = models.EmailField(max_length=200)
	is_leader = models.BooleanField(default=False)
	is_department_leader = models.BooleanField(default=False)

	def __unicode__(self):
		return self.name

members/views.py
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView

from members.models import Member
from groups.models import Group


class MemberListView(ListView):
	template_name = 'members/list.html'
	context_object_name = 'all_members'

	def get_queryset(self):
		""" Return all registered members """
		return Member.objects.all()


class MemberDetailView(DetailView):
	model = Member
	template_name = 'members/detail.html'

	def get_context_data(self, **kwargs):
		context = super(MemberDetailView, self).get_context_data(**kwargs)
		context["member_groups"] = context['member'].member_groups.all()
		context["leader_of_groups"] = Group.objects.filter(leader=context['member'])

		return context


class MemberCreateView(CreateView):
	model = Member
	template_name = 'members/form.html'
	fields = ['name', 'email', 'is_leader', 'is_department_leader']
	success_url = reverse_lazy('members:member_list')


class MemberUpdateView(UpdateView):
	model = Member
	template_name = 'members/form.html'
	fields = ['name', 'email', 'is_leader', 'is_department_leader']
	success_url = reverse_lazy('members:member_list')


class MemberDeleteView(DeleteView):
	model = Member
	template_name = 'members/confirm_delete.html'
	success_url = reverse_lazy('members:member_list')

members/templates/members/confirm_delete.html
{% extends "base.html" %}

{% block content %}

<form method="post">{% csrf_token %}
    Tem certeza que deseja apagar o membro "{{ object }}" ?
    <input type="submit" value="Sim" />
</form>

{% endblock %}

members/templates/members/detail.html
{% extends "base.html" %}

{% block content %}

<div class="col-md-8 col-md-offset-2 content_block">

	<h2>{{ member.name }}</h2>

	<p>E-mail: {{ member.email }}</p>
	<p>
		Líder de GC: 
		{% if member.is_leader %}
			Sim
		{% else %}
			Não
		{% endif %}	
	</p>
	<p>
		Líder de Departamento:
		{% if member.is_deparment_leader %}
			Sim
		{% else %}
			Não
		{% endif %}	
	</p>
	
	<p>Membro dos seguintes GCs: </p>

	{% if member_groups %}
		<ul>
			{% for group in member_groups %}
        		<li>{{ group.name }}</li>
    		{% endfor %}
		</ul>
	{% else %}
		<p>Não é membro de nenhum GC.</p>
	{% endif %}

	<p>É lider dos seguintes GCs: </p>

	{% if leader_of_groups %}
		<ul>
			{% for group in leader_of_groups %}
        		<li>{{ group.name }}</li>
    		{% endfor %}
		</ul>
	{% else %}
		<p>Não é líder de nenhum GC.</p>
	{% endif %}

</div>

{% endblock %}

members/templates/members/form.html
{% extends "base.html" %}

{% block content %}

<h3>Cadastrar novo membro</h3>


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form method="post">

{% csrf_token %}

{{ form.as_p }}

<input type="submit" value="Salvar" />
</form>

{% endblock %}

members/templates/members/list.html
{% extends "base.html" %}

{% block content %}

<div class="col-md-8 col-md-offset-2 content_block">
    
    {% if all_members %}
    
    <table class="entries_table">
        <tbody>
            <tr>
                <th>Nome</th>
                <th>e-mail</th>
                <th>Líder de GC</th>
                <th>Líder de Depart.</th>
            </tr>

            {% for member in all_members %}
            
            <tr>
                <td>
                    <a href="{% url 'members:member_detail' member.id %}">{{ member.name }}</a>
                </td>
                <td>
                    {{ member.email }}
                </td>
                <td align="center">
                    {% if member.is_leader %}
                        Sim
                    {% else %}
                        Não
                    {% endif %}
                </td>
                <td align="center">
                    {% if member.is_department_leader %}
                        Sim
                    {% else %}
                        Não
                    {% endif %}
                </td>
                
                <td>
                    {% if perms.members.change_member %}
                        <a href="{% url 'members:member_update' member.id %}">Editar</a>
                    {% endif %}
                </td>

                <td>
                    {% if perms.members.delete_member %}
                        <a href="{% url 'members:member_delete' member.id %}">Apagar</a>
                    {% endif %}
                </td>
            </tr>
            
            {% endfor %}
        
        </tbody>
    </table>

    {% if perms.members.add_member %}
    <div class="add_entry">
        <a href="{% url 'members:member_add' %}">Novo Membro</a>
    </div>
    {% endif %}

    {% else %}
        <p>Nenhum membro cadastrado.</p>
    {% endif %}
  
</div>

{% endblock %}